Update run-sync-script.yaml

diff --git a/.github/workflows/run-sync-script.yaml b/.github/workflows/run-sync-script.yaml
--- a/.github/workflows/run-sync-script.yaml
+++ b/.github/workflows/run-sync-script.yaml
@@ -40,8 +40,19 @@ jobs:
           else
             echo "No changes detected"
             echo "changes=false" >> $GITHUB_ENV
-          fi
         shell: bash
+
+      - name: Delete and recreate branch
+        if: env.changes == 'true'
+        run: |
+          # Delete the local branch if it exists
+          git branch -D auto-sync-update || echo "Branch not found locally"
+          
+          # Delete the remote branch
+          git push origin --delete auto-sync-update || echo "Branch not found remotely"
+          
+          # Recreate the branch
+          git checkout -b auto-sync-update
 
       - name: Commit and create pull request
         if: env.changes == 'true'
@@ -52,8 +63,6 @@ jobs:
       
           git config --global user.email "$EMAIL"
           git config --global user.name "Max Base (GitHub Actions)"
-      
-          git checkout -b auto-sync-update || git checkout auto-sync-update
       
           if [ -n "$(git status --porcelain)" ]; then
             echo "Unstaged changes detected. Stashing changes."
