Update web-assembly.yml

diff --git a/.github/workflows/web-assembly.yml b/.github/workflows/web-assembly.yml
--- a/.github/workflows/web-assembly.yml
+++ b/.github/workflows/web-assembly.yml
@@ -50,33 +50,30 @@ jobs:
 
           git clone https://github.com/SalamLang/Salam-Editor.git
 
-          cp ./src/salam-wa.js ./Salam-Editor/
-          cp ./src/salam-wa.wasm ./Salam-Editor/
-
           cd Salam-Editor
-          sudo chown www-data:www-data *
           git config user.name "Max Base"
           git config user.email "$EMAIL"
           git config user.name "Max Base"
           git config user.email "${{ secrets.USER_EMAIL }}"
-        
+            
       - name: Calculate checksums of original files
         id: original_checksums
         run: |
           cd src
-          sha256sum salam-wa.js > js-checksum.txt
-          sha256sum salam-wa.wasm > wasm-checksum.txt
+          ls -l salam-wa.js salam-wa.wasm
+          sha256sum salam-wa.js > js-checksum.txt || echo "Error calculating checksum for salam-wa.js"
+          sha256sum salam-wa.wasm > wasm-checksum.txt || echo "Error calculating checksum for salam-wa.wasm"
           
           echo "JS_CHECKSUM=$(cat js-checksum.txt | awk '{ print $1 }')" >> $GITHUB_ENV
           echo "WASM_CHECKSUM=$(cat wasm-checksum.txt | awk '{ print $1 }')" >> $GITHUB_ENV
-
+      
       - name: Calculate checksums of new files in Salam-Editor
         id: new_checksums
         run: |
           cd Salam-Editor
-          
-          sha256sum salam-wa.js > js-checksum-editor.txt || echo "0  salam-wa.js" > js-checksum-editor.txt
-          sha256sum salam-wa.wasm > wasm-checksum-editor.txt || echo "0  salam-wa.wasm" > wasm-checksum-editor.txt
+          ls -l salam-wa.js salam-wa.wasm
+          sha256sum salam-wa.js > js-checksum-editor.txt || echo "Error calculating checksum for salam-wa.js"
+          sha256sum salam-wa.wasm > wasm-checksum-editor.txt || echo "Error calculating checksum for salam-wa.wasm"
           
           echo "JS_CHECKSUM_EDITOR=$(cat js-checksum-editor.txt | awk '{ print $1 }')" >> $GITHUB_ENV
           echo "WASM_CHECKSUM_EDITOR=$(cat wasm-checksum-editor.txt | awk '{ print $1 }')" >> $GITHUB_ENV
@@ -84,7 +81,14 @@ jobs:
       - name: Commit and push changes if needed
         if: ${{ env.JS_CHECKSUM != env.JS_CHECKSUM_EDITOR || env.WASM_CHECKSUM != env.WASM_CHECKSUM_EDITOR }}
         run: |
+          cp ./src/salam-wa.js ./Salam-Editor/
+          cp ./src/salam-wa.wasm ./Salam-Editor/
+
           cd Salam-Editor
+          sudo chown -R www-data:www-data *
+
           git add salam-wa.js salam-wa.wasm
+
           git commit -m "Release: Update WebAssembly files"
+          
           git push https://x-access-token:${{ secrets.USER_TOKEN }}@github.com/SalamLang/Salam-Editor.git
